### ISSUE TITLE
Need to account for multiple locations

### ISSUE THREAD

**Issue by mcelaney** [mcelaney/opportunities#10]
For instance Think Brownstone has 111 S. 15th Street, Mezzanine, Philadelphia PA 19102 in addition to their Conshy location.  This is probably related to #4 in that a position might be remote or a specific location.

**Comment by devNoiseConsulting** [comment]
Add an locale array with an object or objects. The object in this array would have the attributes relavent to the locale. (ie address, location, remote, and positions). 

Remote positions would be placed in a separate locale object or objects that has the remote attribute set. The address and location attributes are optional on this type of locale object.

Here is a sample that I worked up using Think Brownstone as a possible example:
```
  {
    "company": "Think Brownstone",
    "url": "https://www.thinkbrownstone.com/careers/",
    "locale": [
      {
        "address": "201 Fayette St, Conshohocken, PA 19428",
        "location": {
          "lat": 40.074711,
          "lng": -75.305449
        },
        "positions": [
          "Development Lead",
          "Senior Web Developer",
          "Web Developer",
          "Experience Designer- Contractor"
        ]
      },
      {
        "address": "111 S. 15th Street, Mezzanine, Philadelphia, PA 19102",
        "location": {
          "lat": 39.950595,
          "lng": -75.165716
        },
        "positions": [
          "Development Lead",
          "Senior Web Developer",
          "Web Developer",
          "Experience Designer- Contractor"
        ]
      },
      {
        "remote": true,
        "positions": [
          "Development Lead",
          "Senior Web Developer",
          "Web Developer",
          "Experience Designer- Contractor"
        ]
      }
    ]
  },
```

Would there be a need for a locale object to also include an url attribute?

**Comment by devNoiseConsulting** [comment]
I believe a solution to address this issue has been identified in #59.
