### ISSUE TITLE
Add the Date an Opportunity is Added

### ISSUE THREAD

**Issue by mrkplt** [mcelaney/opportunities#31]
I just submitted a pull request for winter interns for i-site, but it occurred to me that information has an expiration date. I don't know when that is, but I think adding the date the opportunity was added might be valuable. Thoughts?

**Comment by devNoiseConsulting** [comment]
My opinion has been to crib properties from Schema.org for our data that matches up. So for the objects in the positions array, I've used properties from the JobPosting schema (https://schema.org/JobPosting). They have a datePosted property that suits your need. It should be a date value in ISO 8601 date format. I suggest using the Calendar Date format  (ie YYYY-MM-DD or YYYYMMDD) from ISO 8601 (https://en.wikipedia.org/wiki/ISO_8601#Calendar_dates).

Could you add datePosted to you winter intern position? I'll hold off on merging your pull request until you can commit this change?

**Comment by mrkplt** [comment]
I added that field. You/I/We may want to add some documentation to the read me on preferred structure for opportunities.

**Comment by devNoiseConsulting** [comment]
Thanks. I've merged your pull request and updated the county/region files to include your changes. 

The preferred structure is still a work in progress as we determine what information people want to see included in companies and positions. 

Updating the readme.md is one of the thing I will try and get to this week.

**Comment by devNoiseConsulting** [comment]
I believe a solution to address this issue has been identified in #59.
