### ISSUE TITLE
Mine http://phldesign.co/jobs/ for companies we don't know about

### ISSUE THREAD

**Issue by mcelaney** [mcelaney/opportunities#35]

**Comment by mcelaney** [comment]
https://github.com/phldesign/phldesign.github.io/blob/master/_data/agencies.yml

**Comment by devNoiseConsulting** [comment]
@mcelaney Working through the list. I've come across a few companies that don't have a job/career url. Do you still want them to have file in the company dir?

**Comment by mcelaney** [comment]
For now I'd like to stick to jobs listed on careers pages... so when there is no career page maybe we include the company in a file but not list the positions

**Comment by devNoiseConsulting** [comment]
Base on what I think you're getting at:
* `url` is for the company's jobs/careers page.
* A new attribute `webSiteUrl` could be used to point to the company's website.
  * This could be useful as some company's job/career page is hosting on another site/service.
* The merge will only include companies that have a `url` attribute.
* The merge will only include companies that have 1 or more position objects.

So I will will need to update the files I generated from the PHLDesign data to not use the `url` attribute. Then change the merge code to follow the new inclusion rules.

Does this sound good to you?
