### ISSUE TITLE
General Applicants

### ISSUE THREAD

**Issue by fbongiovanni29** [mcelaney/opportunities#53]
Curalate has a section labeled "General Applicants". Lots of other companies have something advertising something along the lines of "Don't see a fit shoot us a line anyways". 

I think it would be useful to note these seeing as how I used to skip over companies that may have only had Senior positions. Even companies that may currently only have Android/iOS/Data or non-code related positions open at the moment.

I'd be open to adding them and even doing a full update sometime next week as long as someone's willing to double check the formatting.

**Comment by devNoiseConsulting** [comment]
I personally prefer to see specific job positions. That said I'm not opposed to adding a "General Applicant" position to the company files.

If you have node.js installed, then just run "npm run format" at the top directory for the repo. It will let you know which company files have a JSON formatting problem. Once you've finished updating the companies, run "npm run merge" to update all the county files.

**Comment by fbongiovanni29** [comment]
I agree, it would be annoying seeing General Applicant in the list for every company. Maybe once the app becomes more complex it could be tied into the navigation somehow.

**Comment by mcelaney** [comment]
I'm gonna veto this one.  The "general application" positions are almost always a waste of a candidate's time. Once we get the meta data in here people will be able to filter by interest enough and can cold-apply to any company they want... I'd rather not muddy up the system with positions that are not acually jobs.
